L02P02_2021PC602_2021VA650/Controllers/ComentariosLibroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using L02P02_2021PC602_2021VA650.Models;

namespace L02P02_2021PC602_2021VA650.Controllers
{
    public class ComentariosLibroesController : Controller
    {
        private readonly LibreriaDbContext _context;

        public ComentariosLibroesController(LibreriaDbContext context)
        {
            _context = context;
        }


        public IActionResult SeleccionarLibro(int libroId)
        {
           
            var comentariosLibro = _context.ComentariosLibros.Where(c => c.IdLibro == libroId).ToList();


            return View("~/Views/ComentariosLibroes/Index.cshtml", comentariosLibro);
        }





        // GET: ComentariosLibroes
        public async Task<IActionResult> Index(int id)
        {
            
            ViewData["nombreLibro"] = _context.Libros.FirstOrDefault(l => l.Id == id).Nombre;
            var libreriaDbContext = _context.ComentariosLibros.Include(c => c.IdLibroNavigation);
            return View(await libreriaDbContext.ToListAsync());
        }



       




        // GET: ComentariosLibroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentariosLibro = await _context.ComentariosLibros
                .Include(c => c.IdLibroNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentariosLibro == null)
            {
                return NotFound();
            }

            return View(comentariosLibro);
        }

        // GET: ComentariosLibroes/Create
        public IActionResult Create()
        {
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Id", "Id");
            return View();
        }

        // POST: ComentariosLibroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdLibro,Comentarios,Usuario,CreatedAt")] ComentariosLibro comentariosLibro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comentariosLibro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Id", "Id", comentariosLibro.IdLibro);
            return View(comentariosLibro);
        }

        // GET: ComentariosLibroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentariosLibro = await _context.ComentariosLibros.FindAsync(id);
            if (comentariosLibro == null)
            {
                return NotFound();
            }
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Id", "Id", comentariosLibro.IdLibro);
            return View(comentariosLibro);
        }

        // POST: ComentariosLibroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdLibro,Comentarios,Usuario,CreatedAt")] ComentariosLibro comentariosLibro)
        {
            if (id != comentariosLibro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comentariosLibro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComentariosLibroExists(comentariosLibro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Id", "Id", comentariosLibro.IdLibro);
            return View(comentariosLibro);
        }

        // GET: ComentariosLibroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentariosLibro = await _context.ComentariosLibros
                .Include(c => c.IdLibroNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentariosLibro == null)
            {
                return NotFound();
            }

            return View(comentariosLibro);
        }

        // POST: ComentariosLibroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comentariosLibro = await _context.ComentariosLibros.FindAsync(id);
            if (comentariosLibro != null)
            {
                _context.ComentariosLibros.Remove(comentariosLibro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComentariosLibroExists(int id)
        {
            return _context.ComentariosLibros.Any(e => e.Id == id);
        }
    }
}

L02P02_2021PC602_2021VA650/Controllers/confirmacionController.cs
using L02P02_2021PC602_2021VA650.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace L02P02_2021PC602_2021VA650.Controllers
{

    public class ConfirmacionController : Controller
    {
        private readonly LibreriaDbContext _context;

        public ConfirmacionController(LibreriaDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var libreriaDbContext = _context.ComentariosLibros.Include(c => c.IdLibroNavigation);
            return View(await libreriaDbContext.ToListAsync());
        }
    }
}

L02P02_2021PC602_2021VA650/Views/ComentariosLibroes/Index.cshtml
@model IEnumerable<L02P02_2021PC602_2021VA650.Models.ComentariosLibro>

@{
    ViewData["Title"] = "Listado de Comentarios Por Libros";
}

<div></div>
<div class="container">
    <ul class="progressbar">
        <li>Autores</li>
        <li >Libros</li>
        <li class="active">Comentarios Existentes</li>
        <li >Nuevo Comentario</li>
    </ul>
</div>
</div>

<div class="border border-1 p-4 rounded rounded-1 m-5" style="margin-top:auto">
    <h1 style="color:#504cca">Libro Seleccionado: @ViewData["nombrelibro"]</h1>
    <h1 style="color:#504cca">Autor: @ViewData["nombreautor"]</h1>
</div>
<div class="container">
    <h1>Comentarios del Libro</h1>
    <hr />
    <div></div>
    <div class="container">
        <ul class="progressbar">
            <li>Autores</li>
            <li>Libros</li>
            <li class="active">Comentarios Existentes</li>
            <li>Nuevo Comentario</li>
        </ul>
    </div>

    <div class="d-flex col-12 mt-5">
        <div class="col-6">
            <h2 style="color:#504cca">Comentarios existentes</h2>
            <div class="border border-1 p-4 rounded rounded-1 ">
                <div>
                    @if (Model.Any())
                    {
                        foreach (var comentario in Model)
                        {
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h5 class="card-title">@comentario.Usuario</h5>
                                    <p class="card-text">@comentario.Comentarios</p>

                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <p>No hay comentarios para este libro.</p>
                    }
                </div>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-5">
            <h2 style="color:#504cca">Agregar un comentario</h2>
            <h4>Comentario</h4>
            <textarea name="" id="" cols="30" style="height:200px; width:100%" rows="100"></textarea>
            <div class="border border-1 p-3">
                <button class="btn btn-success w-100" style="text-decoration:none;">
                    @Html.ActionLink("Guardar Comentario", "Index", "Confirmacion", null, new { @class = "btn btn-success seleccionar-libro", style = "color:white;" })
                </button>
            </div>
            </div>

    </div>
</div>